### ISSUE TITLE
[TODO] various nodebox-modeled items that need replaced with mesh nodes, new WiP/Unfinished models, models that need rework

### ISSUE THREAD

**Issue by kilbith** [VanessaE/homedecor_modpack#198]
The following is a list of models in Homedecor Modpack that are either implemented as nodeboxes or some other low-quality shape/drawtype and which would be better-done with mesh nodes, are composed of more than one node, have since been implemented as mesh nodes but which need reworked (i.e. need UV map improvements or tweaks to their shape), or are waiting to be implemented as new nodes (perhaps where the models have not yet been completed to a point where they are suitable for this modpack):

### To add
- [x] Candlestick
- [x] Ceiling light
- [x] Default vessels shelf
- [x] Lava lamps
- [x] Ironing board
- [x] King size bed
- [x] Plasma ball
- [x] Rugs
- [x] Spiral staircase
- [x] Stair banisters
- [x] [Soda Vending Machine](https://github.com/kilbith/soda/archive/master.zip)
- [x] [Tetris Arcade](https://github.com/kilbith/tetris/archive/master.zip)
- [x] Wall Sconce

### To revise
- [x] 3d bookshelf (needs better use of materials/UV maps)
- [x] 3dforniture showerhead
- [x] 4-bottles multicolor
- [x] Analog clock
- [x] Beds (bevels with less angle)
- [x] Desk globe
- [x] Desk/standing lamps (needs better use of materials/UV maps)
- [x] Kitchen sink/cabinet
- [x] Lanterns (all types - needs better UV maps)
- [x] Openframe bookshelf (needs better use of materials/UV maps)
- [x] Picture frame (needs better UV maps)
- [x] Paper towels
- [x] Slopes (needs better UV maps)
- [x] Stereo speakers
- [x] Toilet paper
- [x] Trophy
- [x] Window shutters
- [x] Wine rack

### To convert

- [x] 3D Furniture's armchairs
- [x] 3D Furniture's chains
- [x] 3D Furniture's bathroom sink
- [x] 3D Furniture's torch wall 
- [x] 3D Furniture's toilet
- [x] 3D Furniture's bathroom sink/shower taps
- [x] Air conditioner
- [x] Barbecue
- [x] Bathroom set
- [x] Bedroom wardrobe
- [x] Beds
- [x] Beer tap
- [x] Calendar
- [x] Candles
- [x] CD/DVD cabinet
- [x] Chandelier
- [x] Chimney
- [x] Coat tree
- [x] Coffeemaker
- [x] Computers (only those that really need it)
- [x] Copper pans
- [x] Deck Chair
- [x] Doors (all types)
- [x] Filing cabinet
- [x] Fish tank
- [x] Garden benches (both types)
- [x] Grandfather clock
- [x] Kitchen chairs
- [x] Kitchen faucet
- [x] Mailbox
- [x] Oil lamp
- [x] Radiator heater
- [x] Paintings
- [x] Plasma TV
- [x] Sofas (LRfurn)
- [x] Sport bench
- [x] Telephone
- [x] Tool cabinet
- [x] Towel rod
- [x] Windows blinds

**Comment by kilbith** [comment]
Also, I simplified the bathroom set. Download : https://www.dropbox.com/s/hx0rq6uk8e6td70/bathroom_set.zip

![bathroom_set](https://cloud.githubusercontent.com/assets/7883281/6347854/7e657714-bc1b-11e4-986c-4bc5303948ec.jpg)

**Comment by kilbith** [comment]
Also as reminder : add a **shower water flowing** when the shower_head model will be re-do in mesh. The model will be likely inclined and it will use the particles for the transversal water ejection.

![b7ce3e8a-999a-11e4-88ac-21f6d0b70d42](https://cloud.githubusercontent.com/assets/7883281/6411182/68590104-be76-11e4-9ac4-0963edc1c27b.png)

**Comment by VanessaE** [comment]
All tasks have been completed.

**Comment by Megaf** [comment]
Wow, great work, thanks a million!
